Repository dynamic/silverstripe-flexslider, pull requests merged in 2019-05, with the labels that each got.

#173 DOCS module docs
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  code-of-conduct.md
  docs/en/index.md
Labels: docs, v3

#174 DOCS update module docs
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  code-of-conduct.md
Labels: docs, v4

#178 UPDATE remove .DS_Store
  templates/Dynamic/.DS_Store
  templates/Dynamic/FlexSlider/.DS_Store
Labels: v4

#177 REFACTOR update carousel class to fs-carousel
  css/silverstripe-flexslider.css
  src/ORM/FlexSlider.php
  templates/Includes/FlexSlider.ss
Labels: v4

#176 REFACTOR remove SlidePublishTask
  src/Task/SlideLinkTask.php
  src/Task/SlidePublishTask.php
  src/Task/SlideThumbnailNavMigrationTask.php
Labels: v4

#161 Speed in cms
  _config/config.yml
  lang/en.yml
  src/ORM/FlexSlider.php
  tests/FlexSliderTest.php
  tests/TestPage.php
Labels: v4
